In [1]:
from pathlib import Path as p
import sqlite3 as sq
import pandas as pd

In [2]:
DB_FILENAME = "poke_db.db"

def init_db():
    if not p(DB_FILENAME).is_file():
        p(DB_FILENAME).touch()

In [3]:
init_db()
conn = sq.connect(DB_FILENAME)
c = conn.cursor()
c.execute('''
    CREATE TABLE IF NOT EXISTS Pokemons (idx int, name text,
    type1 text,type2 text, sum_stats int, hp int, attack int,
    special_attack int, defense int, special_defense int, speed int,
    generation int, is_legend boolean)''')

In [4]:
poke_data = pd.read_csv('Pokemon.csv')
poke_data.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [5]:
poke_data.columns = ['idx', 'name', 'type1', 'type2', 
                      'sum_stats', 'hp', 'attack',
                      'special_attack', 'defense',    
                      'special_defense', 'speed', 'generation',
                     'is_legend']

In [6]:
poke_data.to_sql('Pokemons', conn, if_exists='append',
                  index=False)

In [7]:
c.execute('''
        SELECT count(name) FROM sqlite_master WHERE type='table' AND
        name='Pokemons' ''')

In [34]:
poke_name = 'bulbasaur'
poke_name = poke_name.lower()
poke_name = poke_name.capitalize()
result = c.execute('''SELECT * FROM Pokemons WHERE name = ?''', 
                    (poke_name,))
result.fetchone()

(1, 'Bulbasaur', 'Grass', 'Poison', 318, 45, 49, 49, 65, 65, 45, 1, 0)

In [35]:
def get_poke_by_type(type1, type2=None):
    type1 = type1.lower()
    type1 = type1.capitalize()
    conn = sq.connect(DB_FILENAME)
    c = conn.cursor()
    if type2:
        c.execute('''
        SELECT * FROM Pokemons WHERE type1 = ? AND type2 = ?''', 
        (type1, type2))
    else:
        c.execute('''
        SELECT * FROM Pokemons WHERE type1 = ?''', (type1,))
 
    return c.fetchall()

In [39]:
get_poke_by_type('eleCtrIc')

[(25, 'Pikachu', 'Electric', None, 320, 35, 55, 40, 50, 50, 90, 1, 0),
 (26, 'Raichu', 'Electric', None, 485, 60, 90, 55, 90, 80, 110, 1, 0),
 (81, 'Magnemite', 'Electric', 'Steel', 325, 25, 35, 70, 95, 55, 45, 1, 0),
 (82, 'Magneton', 'Electric', 'Steel', 465, 50, 60, 95, 120, 70, 70, 1, 0),
 (100, 'Voltorb', 'Electric', None, 330, 40, 30, 50, 55, 55, 100, 1, 0),
 (101, 'Electrode', 'Electric', None, 480, 60, 50, 70, 80, 80, 140, 1, 0),
 (125, 'Electabuzz', 'Electric', None, 490, 65, 83, 57, 95, 85, 105, 1, 0),
 (135, 'Jolteon', 'Electric', None, 525, 65, 65, 60, 110, 95, 130, 1, 0),
 (145, 'Zapdos', 'Electric', 'Flying', 580, 90, 90, 85, 125, 90, 100, 1, 1),
 (172, 'Pichu', 'Electric', None, 205, 20, 40, 15, 35, 35, 60, 2, 0),
 (179, 'Mareep', 'Electric', None, 280, 55, 40, 40, 65, 45, 35, 2, 0),
 (180, 'Flaaffy', 'Electric', None, 365, 70, 55, 55, 80, 60, 45, 2, 0),
 (181, 'Ampharos', 'Electric', None, 510, 90, 75, 85, 115, 90, 55, 2, 0),
 (181,
  'AmpharosMega Ampharos',
  'Electric',
  'Dragon',
  610,
  90,
  95,
  105,
  165,
  110,
  45,
  2,
  0),
 (239, 'Elekid', 'Electric', None, 360, 45, 63, 37, 65, 55, 95, 2, 0),
 (243, 'Raikou', 'Electric', None, 580, 90, 85, 75, 115, 100, 115, 2, 1),
 (309, 'Electrike', 'Electric', None, 295, 40, 45, 40, 65, 40, 65, 3, 0),
 (310, 'Manectric', 'Electric', None, 475, 70, 75, 60, 105, 60, 105, 3, 0),
 (310,
  'ManectricMega Manectric',
  'Electric',
  None,
  575,
  70,
  75,
  80,
  135,
  80,
  135,
  3,
  0),
 (311, 'Plusle', 'Electric', None, 405, 60, 50, 40, 85, 75, 95, 3, 0),
 (312, 'Minun', 'Electric', None, 405, 60, 40, 50, 75, 85, 95, 3, 0),
 (403, 'Shinx', 'Electric', None, 263, 45, 65, 34, 40, 34, 45, 4, 0),
 (404, 'Luxio', 'Electric', None, 363, 60, 85, 49, 60, 49, 60, 4, 0),
 (405, 'Luxray', 'Electric', None, 523, 80, 120, 79, 95, 79, 70, 4, 0),
 (417, 'Pachirisu', 'Electric', None, 405, 60, 45, 70, 45, 90, 95, 4, 0),
 (462, 'Magnezone', 'Electric', 'Steel', 535, 70, 70, 115, 130, 90, 60, 4, 0),
 (466, 'Electivire', 'Electric', None, 540, 75, 123, 67, 95, 85, 95, 4, 0),
 (479, 'Rotom', 'Electric', 'Ghost', 440, 50, 50, 77, 95, 77, 91, 4, 0),
 (479,
  'RotomHeat Rotom',
  'Electric',
  'Fire',
  520,
  50,
  65,
  107,
  105,
  107,
  86,
  4,
  0),
 (479,
  'RotomWash Rotom',
  'Electric',
  'Water',
  520,
  50,
  65,
  107,
  105,
  107,
  86,
  4,
  0),
 (479,
  'RotomFrost Rotom',
  'Electric',
  'Ice',
  520,
  50,
  65,
  107,
  105,
  107,
  86,
  4,
  0),
 (479,
  'RotomFan Rotom',
  'Electric',
  'Flying',
  520,
  50,
  65,
  107,
  105,
  107,
  86,
  4,
  0),
 (479,
  'RotomMow Rotom',
  'Electric',
  'Grass',
  520,
  50,
  65,
  107,
  105,
  107,
  86,
  4,
  0),
 (522, 'Blitzle', 'Electric', None, 295, 45, 60, 32, 50, 32, 76, 5, 0),
 (523, 'Zebstrika', 'Electric', None, 497, 75, 100, 63, 80, 63, 116, 5, 0),
 (587, 'Emolga', 'Electric', 'Flying', 428, 55, 75, 60, 75, 60, 103, 5, 0),
 (602, 'Tynamo', 'Electric', None, 275, 35, 55, 40, 45, 40, 60, 5, 0),
 (603, 'Eelektrik', 'Electric', None, 405, 65, 85, 70, 75, 70, 40, 5, 0),
 (604, 'Eelektross', 'Electric', None, 515, 85, 115, 80, 105, 80, 50, 5, 0),
 (642,
  'ThundurusIncarnate Forme',
  'Electric',
  'Flying',
  580,
  79,
  115,
  70,
  125,
  80,
  111,
  5,
  1),
 (642,
  'ThundurusTherian Forme',
  'Electric',
  'Flying',
  580,
  79,
  105,
  70,
  145,
  80,
  101,
  5,
  1),
 (694, 'Helioptile', 'Electric', 'Normal', 289, 44, 38, 33, 61, 43, 70, 6, 0),
 (695, 'Heliolisk', 'Electric', 'Normal', 481, 62, 55, 52, 109, 94, 109, 6, 0),
 (702, 'Dedenne', 'Electric', 'Fairy', 431, 67, 58, 57, 81, 67, 101, 6, 0)]